services:

  netcat:
    image: veturo98/server-ssh:1.1
    restart: always
    command: bash -c "/usr/sbin/sshd -D" # Questo comando non termina mai
    healthcheck:
      test: ["CMD", "echo", "test"]  
      interval: 10s
      timeout: 5s 
      retries: 2
    ports:
      - ${PORTA}:22
    