services:

  netcat:
    image: ubuntu:latest
    restart: always
    command: tail -f /dev/null # Questo comando non termina mai
    healthcheck:
      test: ["CMD", "echo", "test"]  
      interval: 10s
      timeout: 5s 
      retries: 2
    ports:
      - ${PORTA}:22
    