services:

  db:
    image: postgres
    restart: always
 
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: sase-db
 
      

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    
    environment:
      PGADMIN_DEFAULT_EMAIL: user@sadsecurity.it
      PGADMIN_DEFAULT_PASSWORD:  password


  
